### ISSUE TITLE
join doesn't work on 'Potato Virus Y'

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#13] opened 2015-12-03 22:21 UTC
For this dataset there are several spectra csv files and one metadata xlsx file.  The join field that is specified is Plant_ID.

Row preview reports "Matches: none"

**Comment by jrmerz** [comment] 2015-12-03 23:35
This is an interesting scenario.  So the csv files are read in using the python standard library csv parser and all values are parsed as strings.  The excel file is being read in using xlrd (https://pypi.python.org/pypi/xlrd) which is reading the type information for the column, in this case a number, parsing the column as such, then I convert to string.  Which seems to be producing 2.0 instead of 2.  I need to dive into a little bit about how xlrd is deciding on type (my guess is it's assigning numbers to floats and not ints) as well as pythons number to string conversion.  I want to keep any precision defined in a excel file but not add any (which is happening in this case).

**Comment by jrmerz** [comment] 2015-12-04 00:00
So was correct, number columns are parsed as floats (so 3.0 instead of 3): https://secure.simplistix.co.uk/svn/xlrd/trunk/xlrd/doc/xlrd.html?p=4966#sheet.Cell-class .  There are no great solutions here.  You can upload the file as a csv or you can mark the column as a string.  Otherwise the columns will always be interpreted as a miss match.

**Comment by ckingdon** [comment] 2015-12-04 00:04
I think I flagged this at previously .. strings interpreted as float.

Can you dictate that, if a user is going to join on a field, it will be interpreted as a string rather than a float. There aren't any situations I can think of where one would join on a floating point number.

**Comment by jrmerz** [comment] 2015-12-04 00:13
Everything in the system is stored as a string.  The problem is I don't have control over the excel parser.  The parser reads the excel file and hands my code the values.  At which point, number column cells are floats.  I then convert to a string.  So 3 is converted to 3.0 before my code executes.

You could say, well I am aware of this issue, so if my column is marked as a join column and matches /\d+\.0/ go back and remove the '.0' from the string... but this is just a guess.  Let's say I wanted 3.0 as my id and in my csv file I passed 3.0 as well.  Then I would have the opposite miss match.

**Comment by jrmerz** [comment] 2015-12-04 00:15
Also, when you say 'strings interpreted as float', when I downloaded the file, the column was marked as a number, no?  If you mark the column as a string, this should work.

**Comment by ckingdon** [comment] 2015-12-04 17:02
Just now, I downloaded the file, used Excel to change the format of column Plant_ID from "General" to "Text", the uploaded and tried to join on Plant_ID. 

The problem persists. 3 becomes 3.0 and the join is not possible.

In general, not many people are going to use an integer as their unique identifier (that CKAN will subsequently turn to a float), but it will happen. I understand the technical limitations, but I think we'll need to discuss to come up with a plan.

**Comment by jrmerz** [comment] 2016-03-01 22:13
As this is a known, ongoing issue with no real solution in site.  Going to close for now.

**Closed by jrmerz** 2016-03-01 22:13 UTC
