### ISSUE TITLE
License provided but does not show on published dataset

### ISSUE THREAD

**Issue by amrutavidwans** [CSTARS/ckanext-ecosis#86] opened 2022-01-19 21:41 UTC
I provided 'Other (Not Open)' while creating test dataset, but it created the dataset with the license field blank. When I clicked publish, I was able to publish with the license field empty.
I was emailed this link for the search http://dev-search.ecosis.org/#result/4873f7c1-8a94-4565-b1c8-d954cda66ad7

**Comment by jrmerz** [comment] 2022-05-22 17:36
tested locally, unable to reproduce.  closing for now.

**Closed by jrmerz** 2022-05-22 17:36 UTC
